FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine@sha256:ed94db9b569b9315978fd54a7cb5f95f23229746493d91dc5c5d122d0fcfe368

# Installa Dalamud dalla ultima release stable
ENV DALAMUD_HOME=/lib/dalamud
WORKDIR ${DALAMUD_HOME}
RUN wget -O dalamud.zip https://goatcorp.github.io/dalamud-distrib/latest.zip
RUN unzip dalamud.zip
RUN rm dalamud.zip

# Torna alla directory di Default
WORKDIR /