FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine@sha256:3ae795284d2c08bdad7b310852b84442f1c75bcdc7420ec5eb85088dd5a6a906

# Installa Dalamud dalla ultima release stable
ENV DALAMUD_HOME=/lib/dalamud
WORKDIR ${DALAMUD_HOME}
RUN wget -O dalamud.zip https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
RUN unzip dalamud.zip
RUN rm dalamud.zip

# Torna alla directory di Default
WORKDIR /