FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine@sha256:5f137562bdaa71c68837f473f5b8bc6b3c24a974c6bcf8eeaf8d01a66ed085f5

# Installa Dalamud dalla ultima release stable
ENV DALAMUD_HOME=/lib/dalamud
WORKDIR ${DALAMUD_HOME}
RUN wget -O dalamud.zip https://goatcorp.github.io/dalamud-distrib/latest.zip
RUN unzip dalamud.zip
RUN rm dalamud.zip

# Torna alla directory di Default
WORKDIR /