FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine@sha256:35a2466e5e86f94bfe95efb9c10012edd970de74fa15c668d61fade809e89f35

# Installa Dalamud dalla ultima release stable
ENV DALAMUD_HOME=/lib/dalamud
WORKDIR ${DALAMUD_HOME}
RUN wget -O dalamud.zip https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
RUN unzip dalamud.zip
RUN rm dalamud.zip

# Torna alla directory di Default
WORKDIR /