FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine@sha256:e4de075cb8a1ab944722a2b8ec0c11855da48880588a3b086e38739e1a9828d6

# Installa Dalamud dalla ultima release stable
ENV DALAMUD_HOME=/lib/dalamud
WORKDIR ${DALAMUD_HOME}
RUN wget -O dalamud.zip https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
RUN unzip dalamud.zip
RUN rm dalamud.zip

# Torna alla directory di Default
WORKDIR /